---
- name: install ansible selinux support library
  become: True
  package:
    name: libselinux-python
    state: present

- name: install ansible selinux configure libraries
  become: True
  package:
    name: "{{ pkg_name }}"
    state: present
  when: ansible_selinux.status == "enabled"
  var:
    pkg_name:
      - policycoreutils-python
      - libsemanage-python
